"use strict";(()=>{var e={};e.id=8945,e.ids=[8945],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},82243:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>f,patchFetch:()=>x,requestAsyncStorage:()=>d,routeModule:()=>u,serverHooks:()=>h,staticGenerationAsyncStorage:()=>m});var n={};r.r(n),r.d(n,{POST:()=>c});var o=r(49303),a=r(88716),i=r(60670),s=r(87070),l=r(1473);async function c(e){try{let t=await (0,l.Z)(e);if(t instanceof s.NextResponse)return t;let r=await e.json();if(!r.images||0===r.images.length)return s.NextResponse.json({error:"No images provided"},{status:400});let n=process.env.OPENAI_API_KEY;if(!n)return s.NextResponse.json({error:"OpenAI API key not configured"},{status:500});let o=[];for(let e of r.images)try{let t=await p(e.base64,e.mimeType,n);t&&o.push(t)}catch(e){console.error("Failed to extract from image:",e)}if(0===o.length)return s.NextResponse.json({success:!1,error:"Could not extract any data from the images"});let a=function(e){let t={};for(let r of e)r.name&&!t.name&&(t.name=r.name),r.company&&!t.company&&(t.company=r.company),r.jobTitle&&!t.jobTitle&&(t.jobTitle=r.jobTitle),r.email&&!t.email&&(t.email=r.email),r.phone&&!t.phone&&(t.phone=r.phone),r.website&&!t.website&&(t.website=r.website),r.linkedInUrl&&!t.linkedInUrl&&(t.linkedInUrl=r.linkedInUrl),r.twitterUrl&&!t.twitterUrl&&(t.twitterUrl=r.twitterUrl),r.location&&!t.location&&(t.location=r.location),r.additionalInfo&&(t.additionalInfo=t.additionalInfo?`${t.additionalInfo}; ${r.additionalInfo}`:r.additionalInfo);return t}(o);return s.NextResponse.json({success:!0,extractedData:a})}catch(e){return console.error("Scan API error:",e),s.NextResponse.json({success:!1,error:e.message||"Internal server error"},{status:500})}}async function p(e,t,r){let n=`You are an expert at reading business cards and extracting contact information.
Analyze the image and extract ALL visible information.

Return ONLY a valid JSON object with these fields (omit fields that are not visible):
{
  "name": "Full name of the person",
  "company": "Company or organization name",
  "jobTitle": "Job title or position",
  "email": "Email address",
  "phone": "Phone number(s)",
  "website": "Website URL",
  "linkedInUrl": "LinkedIn profile URL if visible",
  "twitterUrl": "Twitter/X handle or URL if visible",
  "location": "Address or location",
  "additionalInfo": "Any other relevant information (certifications, taglines, etc.)"
}

IMPORTANT:
- Extract the EXACT text as shown on the card
- For names, include any titles (Dr., Eng., etc.)
- For URLs, include the full URL if visible
- If a field is not visible or unclear, omit it from the JSON
- Return ONLY the JSON, no explanation`,o=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${r}`},body:JSON.stringify({model:"gpt-4o",messages:[{role:"system",content:n},{role:"user",content:[{type:"text",text:"Extract all contact information from this business card image:"},{type:"image_url",image_url:{url:`data:${t};base64,${e}`,detail:"high"}}]}],max_tokens:1e3,temperature:.1})});if(!o.ok){let e=await o.json().catch(()=>({}));throw console.error("GPT-4o vision API error:",o.status,e),Error(`GPT-4o API error: ${o.status}`)}let a=await o.json(),i=a.choices[0]?.message?.content;if(!i)return null;try{let e=i.trim();return e.startsWith("```")&&(e=e.replace(/^```(?:json)?\s*\n?/,"").replace(/\n?```\s*$/,"")),JSON.parse(e)}catch(e){return console.error("Failed to parse GPT response:",i),null}}let u=new o.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/api/explorer/scan/route",pathname:"/api/explorer/scan",filename:"route",bundlePath:"app/api/explorer/scan/route"},resolvedPagePath:"C:\\Users\\user\\Desktop\\Ammars_Work\\pressure_project\\p2p-app\\frontend\\src\\app\\api\\explorer\\scan\\route.ts",nextConfigOutput:"standalone",userland:n}),{requestAsyncStorage:d,staticGenerationAsyncStorage:m,serverHooks:h}=u,f="/api/explorer/scan/route";function x(){return(0,i.patchFetch)({serverHooks:h,staticGenerationAsyncStorage:m})}},1473:(e,t,r)=>{r.d(t,{Z:()=>o});var n=r(87070);async function o(e){let t=e.headers.get("authorization");if(!t?.startsWith("Bearer "))return n.NextResponse.json({error:"Authentication required"},{status:401});try{let e=await fetch("https://intellmatch.com/api/v1/auth/me",{headers:{Authorization:t}});if(!e.ok)return n.NextResponse.json({error:"Invalid or expired token"},{status:401});let r=await e.json();return{userId:r.data?.id||r.data?.userId}}catch{return n.NextResponse.json({error:"Authentication service unavailable"},{status:503})}}}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),n=t.X(0,[9276,5972],()=>r(82243));module.exports=n})();