
ALERT_EMAIL=""


TELEGRAM_BOT_TOKEN="8591466481:AAFjm07cUQHMQ0ZCkXyODZCUQpZMgcI-7k8"
TELEGRAM_CHAT_ID="1301916789"


SLACK_WEBHOOK_URL=""


DISCORD_WEBHOOK_URL=""

ALERT_COOLDOWN_SECONDS=300
echo "# intellmatchai_deploy_test" >> README.md
